import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#f2f2f2',
  },
  container: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 32,
    paddingBottom: 32,
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
    color: '#222222',
  },
  pathLabel: {
    marginTop: 20,
    fontSize: 12,
    fontWeight: '600',
    color: '#666666',
    textTransform: 'uppercase',
    letterSpacing: 0.2,
  },
  pathValue: {
    marginTop: 6,
    marginBottom: 8,
    fontSize: 15,
    color: '#222222',
    fontWeight: '500',
  },
  upButton: {
    alignSelf: 'flex-start',
    marginTop: 8,
    marginBottom: 18,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 4,
    backgroundColor: '#d9d9d9',
    borderWidth: 1,
    borderColor: '#b5b5b5',
  },
  upButtonDisabled: {
    backgroundColor: '#e5e5e5',
    borderColor: '#cfcfcf',
  },
  upButtonPressed: {
    opacity: 0.85,
  },
  upButtonText: {
    color: '#222222',
    fontSize: 14,
    fontWeight: '600',
  },
  storageCard: {
    backgroundColor: '#ffffff',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#d0d0d0',
    padding: 16,
    marginBottom: 14,
  },
  storageRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  storageLabel: {
    flex: 1,
    fontSize: 14,
    color: '#555555',
    paddingRight: 12,
  },
  storageValue: {
    fontSize: 14,
    fontWeight: '600',
    color: '#222222',
  },
  formSection: {
    backgroundColor: '#ffffff',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#d0d0d0',
    padding: 16,
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#222222',
    marginBottom: 12,
  },
  input: {
    borderWidth: 1,
    borderColor: '#bdbdbd',
    borderRadius: 4,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    color: '#222222',
    backgroundColor: '#ffffff',
    marginBottom: 10,
  },
  textArea: {
    minHeight: 88,
  },
  actionButton: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
    paddingVertical: 12,
    backgroundColor: '#d9d9d9',
    borderWidth: 1,
    borderColor: '#b5b5b5',
  },
  fileButton: {
    backgroundColor: '#d9d9d9',
  },
  actionButtonPressed: {
    opacity: 0.88,
  },
  actionButtonText: {
    color: '#222222',
    fontSize: 14,
    fontWeight: '600',
  },
  infoRow: {
    marginBottom: 10,
  },
  infoLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#666666',
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  infoValue: {
    fontSize: 14,
    color: '#222222',
    fontWeight: '500',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.25)',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  modalCard: {
    backgroundColor: '#ffffff',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#d0d0d0',
    padding: 16,
    maxHeight: '85%',
  },
  closeModalButton: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
    paddingVertical: 12,
    marginTop: 6,
    backgroundColor: '#d9d9d9',
    borderWidth: 1,
    borderColor: '#b5b5b5',
  },
  viewerHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  viewerTitleWrap: {
    flex: 1,
    paddingRight: 12,
  },
  viewerLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#666666',
    textTransform: 'uppercase',
    letterSpacing: 0.2,
  },
  viewerTitle: {
    marginTop: 6,
    fontSize: 18,
    fontWeight: '700',
    color: '#222222',
  },
  viewerEditor: {
    minHeight: 220,
    maxHeight: 320,
    marginBottom: 10,
  },
  viewerLoadingWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 24,
  },
  viewerHint: {
    marginBottom: 12,
    fontSize: 14,
    color: '#666666',
  },
  saveButton: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
    paddingVertical: 12,
    backgroundColor: '#d9d9d9',
    borderWidth: 1,
    borderColor: '#b5b5b5',
  },
  saveButtonDisabled: {
    backgroundColor: '#e5e5e5',
    borderColor: '#cfcfcf',
  },
  closeButton: {
    borderRadius: 4,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: '#d9d9d9',
    borderWidth: 1,
    borderColor: '#b5b5b5',
  },
  closeButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#222222',
  },
  listTitle: {
    marginBottom: 12,
    fontSize: 16,
    fontWeight: '700',
    color: '#222222',
  },
  listContent: {
    paddingTop: 4,
    paddingBottom: 32,
  },
  emptyListContent: {
    flexGrow: 1,
    paddingTop: 4,
    paddingBottom: 32,
  },
  itemCard: {
    backgroundColor: '#fff',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#d0d0d0',
    overflow: 'hidden',
  },
  itemMainArea: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  itemCardPressed: {
    backgroundColor: '#ebebeb',
  },
  itemTextWrap: {
    flex: 1,
  },
  itemName: {
    fontSize: 15,
    fontWeight: '500',
    color: '#222222',
  },
  itemMeta: {
    marginTop: 2,
    fontSize: 13,
    color: '#666666',
  },
  itemArrow: {
    fontSize: 20,
    color: '#777777',
  },
  itemActions: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: '#d0d0d0',
  },
  infoButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    backgroundColor: '#eeeeee',
    borderRightWidth: 1,
    borderRightColor: '#d0d0d0',
  },
  infoButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#222222',
  },
  deleteButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    backgroundColor: '#eeeeee',
  },
  deleteButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#222222',
  },
  separator: {
    height: 10,
  },
  centerState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  stateText: {
    marginTop: 12,
    fontSize: 14,
    lineHeight: 22,
    color: '#555555',
    textAlign: 'center',
  },
  errorText: {
    fontSize: 14,
    lineHeight: 22,
    color: '#444444',
    textAlign: 'center',
  },
});

export default styles;
